name: CI/CD ToDolist

on: 
  push:
    branches:
      - main
env:
  NODE_VERSION: "18.18"

jobs:
  Todolist:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Hola"
    